name: africar
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  cached_network_image: ^3.2.1
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  geocoding: ^2.0.5
  get_it: ^7.2.0
  iconsax: ^0.0.8
  intl: ^0.17.0
  ionicons: ^0.2.1
  line_icons: ^2.0.1
  location: ^4.4.0
  provider: ^6.0.3
  share_plus: ^4.1.0
  shared_preferences: ^2.0.15
  url_launcher: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/images/brand_logos/

  fonts:
    - family: Avenir
      fonts:
        - asset: assets/fonts/Avenir/Avenir-Black.otf
        - asset: assets/fonts/Avenir/Avenir-BlackOblique.otf
        - asset: assets/fonts/Avenir/Avenir-Book.otf
        - asset: assets/fonts/Avenir/Avenir-BookOblique.otf
        - asset: assets/fonts/Avenir/Avenir-Heavy.otf
        - asset: assets/fonts/Avenir/Avenir-HeavyOblique.otf
        - asset: assets/fonts/Avenir/Avenir-Light.otf
        - asset: assets/fonts/Avenir/Avenir-LightOblique.otf
        - asset: assets/fonts/Avenir/Avenir-Medium.otf
        - asset: assets/fonts/Avenir/Avenir-MediumOblique.otf
        - asset: assets/fonts/Avenir/Avenir-Oblique.otf
        - asset: assets/fonts/Avenir/Avenir-Roman.otf
