final List<Map<String, dynamic>> carBrands = [
  {'name': 'Acura', 'logo': 'assets/images/brand_logos/Acura.png'},
  {'name': 'Alfa Romeo', 'logo': 'assets/images/brand_logos/Alfa_Romeo.png'},
  {
    'name': 'Aston Martin',
    'logo': 'assets/images/brand_logos/Aston_Martin.png'
  },
  {'name': 'Audi', 'logo': 'assets/images/brand_logos/Audi.png'},
  {'name': 'Bentley', 'logo': 'assets/images/brand_logos/Bentley.png'},
  {'name': 'BMW', 'logo': 'assets/images/brand_logos/BMW.png'},
  {'name': 'Buick', 'logo': 'assets/images/brand_logos/Buick.png'},
  {'name': 'Cadillac', 'logo': 'assets/images/brand_logos/Cadillac.png'},
  {'name': 'Chevrolet', 'logo': 'assets/images/brand_logos/Chevrolet.png'},
  {'name': 'Chrysler', 'logo': 'assets/images/brand_logos/Chrysler.png'},
  {'name': 'Dodge', 'logo': 'assets/images/brand_logos/Dodge.png'},
  {'name': 'Ferrari', 'logo': 'assets/images/brand_logos/Ferrari.png'},
  {'name': 'Fiat', 'logo': 'assets/images/brand_logos/FIAT.png'},
  {'name': 'Ford', 'logo': 'assets/images/brand_logos/Ford.png'},
  {'name': 'Genesis', 'logo': 'assets/images/brand_logos/Genesis.png'},
  {'name': 'GMC', 'logo': 'assets/images/brand_logos/GMC.png'},
  {'name': 'Honda', 'logo': 'assets/images/brand_logos/Honda.png'},
  {'name': 'Hyundai', 'logo': 'assets/images/brand_logos/Hyundai.png'},
  {'name': 'Infiniti', 'logo': 'assets/images/brand_logos/INFINITI.png'},
  {'name': 'Jaguar', 'logo': 'assets/images/brand_logos/Jaguar.png'},
  {'name': 'Jeep', 'logo': 'assets/images/brand_logos/Jeep.png'},
  {'name': 'Kia', 'logo': 'assets/images/brand_logos/Kia.png'},
  {'name': 'Lamborghini', 'logo': 'assets/images/brand_logos/Lamborghini.png'},
  {'name': 'Land Rover', 'logo': 'assets/images/brand_logos/Land_Rover.png'},
  {'name': 'Lexus', 'logo': 'assets/images/brand_logos/Lexus.png'},
  {'name': 'Lincoln', 'logo': 'assets/images/brand_logos/Lincoln.png'},
  {'name': 'Maserati', 'logo': 'assets/images/brand_logos/Maserati.png'},
  {'name': 'Mazda', 'logo': 'assets/images/brand_logos/Mazda.png'},
  {'name': 'McLaren', 'logo': 'assets/images/brand_logos/McLaren.png'},
  {'name': 'Mercedes Benz', 'logo': 'assets/images/brand_logos/Mercedes-Benz.png'},
  {'name': 'Mini', 'logo': 'assets/images/brand_logos/MINI.png'},
  {'name': 'Mitsubishi', 'logo': 'assets/images/brand_logos/Mitsubishi.png'},
  {'name': 'Nissan', 'logo': 'assets/images/brand_logos/Nissan.png'},
  {'name': 'Ram', 'logo': 'assets/images/brand_logos/Ram.png'},
  {'name': 'Rolls Royce', 'logo': 'assets/images/brand_logos/Rolls-Royce.png'},
  {'name': 'Subaru', 'logo': 'assets/images/brand_logos/Subaru.png'},
  {'name': 'Tesla', 'logo': 'assets/images/brand_logos/Tesla.png'},
  {'name': 'Toyota', 'logo': 'assets/images/brand_logos/Toyota.png'},
  {'name': 'Volkswagen', 'logo': 'assets/images/brand_logos/Volkswagen.png'},
  {'name': 'Volvo', 'logo': 'assets/images/brand_logos/Volvo.png'},
  // {'name': '', 'logo': 'assets/images/brand_logos/.png'},
  // {'name': '', 'logo': 'assets/images/brand_logos/.png'},
  // {'name': '', 'logo': 'assets/images/brand_logos/.png'},
];
